### ISSUE TITLE
Import of xr-scipy with scipy >= 1.6.0 fails

### ISSUE THREAD

**Issue by seidlj** [fujiisoup/xr-scipy#8]
In version `1.6.0`, scipy [renamed some methods in `scipy.integrate`](https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html#scipy-integrate-improvements). It has kept the old methods for backward compatibility, but changed their docstrings. This is a problem for `xr-scipy`, because it assumes that the docstrings contain parameter `y` https://github.com/fujiisoup/xr-scipy/blob/8ff001ded269c37a7edafd09535c49c04670a48f/xrscipy/integrate.py#L47 which is not true for the deprecated methods.

As a result, import of `xr-scipy` with `scipy >= 1.6.0` fails with `KeyError: 'y'`.

I can send a PR that fixes this issue and adds the new method names into `xr-scipy`, if you are interested.

**Comment by fujiisoup** [comment]
@seidlj Thank you for pointing this out.

> I can send a PR that fixes this issue and adds the new method names into xr-scipy, if you are interested.

It would be very nice!
